# Generated by Django 5.1.1 on 2024-09-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copywriter', '0002_works'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='work',
            new_name='works',
        ),
    ]
