# Generated by Django 5.1.1 on 2024-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriter', '0003_rename_work_works_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
