# Generated by Django 5.1.1 on 2024-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriter', '0005_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='niche',
            field=models.TextField(null=True),
        ),
    ]
