# Generated by Django 5.1.1 on 2024-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
