# Generated by Django 5.1.1 on 2024-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rating_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecl',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
