# Generated by Django 5.1.1 on 2024-10-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_profilecl_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecl',
            name='rate',
        ),
    ]
