# Generated by Django 5.1.1 on 2024-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sender', models.CharField(max_length=122, null=True)),
                ('user_receiver', models.CharField(max_length=122, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
