# Generated by Django 5.1.1 on 2024-10-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
